"""add focus and seo fields to blog

Revision ID: ccf48f36aab4
Revises: 
Create Date: 2026-01-13 22:24:08.481688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf48f36aab4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focus_keyword', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('secondary_keyword', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.String(length=300), nullable=True))
        batch_op.drop_column('seo_title')
        batch_op.drop_column('seo_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seo_description', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('seo_title', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('meta_description')
        batch_op.drop_column('secondary_keyword')
        batch_op.drop_column('focus_keyword')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
